-- 계정 생성 후 데이터베이스 활용

-- 1) 새로운 계정 만들기
-- CREATE USER 'ohgiraffers'@'%' IDENTIFIED BY  'ohgiraffers';

-- 현재 존재하는 데이터베이스 확인
-- SHOW databases;

-- mysql 데이터베이스로 계정 정보 확인하기
USE mysql;	

SELECT * FROM user;	

-- 2) 데이터베이스 생성 후 계정에 권한 부여
-- 데이터베이스(스키마) 생성
CREATE DATABASE javachipdb;
-- CREATE SCHEMA udb;

GRANT ALL PRIVILEGES ON javachipdb.* TO 'ohgiraffers'@'%';

SHOW GRANTS FOR 'ohgiraffers'@'%';

USE javachipdb;

-- 테이블 삭제
DROP TABLE WORK_SCHEDULE;
DROP TABLE WORK_SCHEDULE_NEXTWEEK;
DROP TABLE ATTENDANCE_INFO;
DROP TABLE JAVACHIP;

CREATE TABLE JAVACHIP_MEMBER
(   
    JAVACHIP_CODE   INTEGER AUTO_INCREMENT NOT NULL COMMENT  '사원번호',
    JAVACHIP_ID    VARCHAR(20) NOT NULL COMMENT 'ID',
    JAVACHIP_PW    VARCHAR(25) NOT NULL COMMENT 'PW',
    POSITION    VARCHAR(10) NOT NULL COMMENT '직책',
    JAVACHIP_NAME VARCHAR(20) NOT NULL COMMENT '이름', 
    PRIMARY KEY(JAVACHIP_CODE)
)ENGINE = 'INNODB'COMMENT = 'JAVACHIP';

ALTER TABLE JAVACHIPDB
 ADD CONSTRAINT JAVACHIPDB_PK PRIMARY KEY ( JAVACHIP_CODE );

CREATE TABLE ATTENDANCE_INFO
(
    JAVACHIP_CODE   INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL COMMENT  '사원번호',
    WORK_HOUR    INTEGER NOT NULL COMMENT '총근무시간',
    REMAIN_VACATION    INTEGER NOT NULL COMMENT '남은연차',
    WORK_STATUS    VARCHAR(20) NOT NULL COMMENT '당일근무현황',
    ARRIVE_INFO    VARCHAR(20) COMMENT '출근정보',
    LEAVE_INFO    BOOLEAN NOT NULL COMMENT '퇴근정보',
    FOREIGN KEY(JAVACHIP_CODE) REFERENCES JAVACHIP_MEMBER(JAVACHIP_CODE)
) ENGINE = 'INNODB'COMMENT = '근태정보';

ALTER TABLE ATTENDANCE_INFO
 ADD CONSTRAINT ATTENDANCE_INFO_PK PRIMARY KEY ( JAVACHIP_CODE );
 
CREATE TABLE WORK_SCHEDULE
(
		JAVACHIP_CODE    INTEGER NOT NULL COMMENT '사원번호',
    DAYS    VARCHAR(20) NOT NULL COMMENT '요일',
    DAY_SCHEDULE    VARCHAR(20) COMMENT '일정',
		FOREIGN KEY(JAVACHIP_CODE) REFERENCES JAVACHIP_MEMBER(JAVACHIP_CODE)
)ENGINE = 'INNODB' COMMENT = '일정';

 
CREATE TABLE WORK_SCHEDULE_NEXTWEEK
(
		JAVACHIP_CODE    INTEGER NOT NULL COMMENT '사원번호',
    DAYS    VARCHAR(20) NOT NULL COMMENT '요일',
    DAY_SCHEDULE    VARCHAR(20) COMMENT '일정',
 FOREIGN KEY(JAVACHIP_CODE) REFERENCES JAVACHIP_MEMBER(JAVACHIP_CODE)
)ENGINE = 'INNODB' COMMENT = '일정';
