SELECT 
      JAVACHIP_CODE,
      JAVACHIP_ID,
      JAVACHIP_PW,
      POSITION,
      JAVACHIP_NAME
FROM JAVACHIP_MEMBER;

INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER01','01','인턴','김인턴');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER02','02','직원','김사원');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER03','03','대리','김대리');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER04','04','주임','김대리');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER05','05','과장','김과장');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER06','06','차장','김차장');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER07','07','부장','김부장');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER08','08','전무','김부장');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER09','09','대표','김대표');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER10','05','부장','유재석');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER11','09','차장','박명수');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER12','151','사원','하하');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER13','0154','인턴','김종국');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER14','6582','인턴','유재석');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER15','1563','사원','송지효');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER16','05011','부장','지석진');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER17','8963','차장','이광수');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER18','dc2522','대리','송중기');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER19','0699q','과장','차태현');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER20','!1250','전무','공유');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER21','hoho','전무','이동욱');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER22','df23','본부장','서인국');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER23','2032','팀장','송강');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER24','7894','팀장','이진욱');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER25','5461','사원','이서연');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER26','26','인턴','손흥민');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER27','27','사원','김민재');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER28','28','사원','황희찬');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER29','29','주임','백승호');
INSERT INTO JAVACHIP_MEMBER(JAVACHIP_CODE,JAVACHIP_ID,JAVACHIP_PW,POSITION,JAVACHIP_NAME)
    VALUES(NULL,'USER30','30','주임','TOM');



SELECT 
    JAVACHIP_CODE,
    WORK_HOUR,
    REMAIN_VACATION,
    WORK_STATUS,
    ARRIVE_INFO,
    LEAVE_INFO
FROM ATTENDANCE_INFO;

INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 9, 5, '재실', '출근', false);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 32, 9, '재실', '출근', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 40, 4, '부재', NULL, TRUE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 24, 12, '부재', '결근', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 16, 2, '재실', '지각', false);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 40, 10, '부재', '출근', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 20, 6, '재실', '출근', false);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 23, 7, '부재', '출근', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 8, 8, '재실', '출근', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 2, 8, '재실', '출근', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 32, 12, '재실', '출근', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 24, 5, '재실', '출근', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 16, 7, '부재', '결근', TRUE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 15, 10, '부재', NULL, TRUE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 40, 13, '재실', '출근', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 38, 12, '재실', '지각', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 24, 5, '부재', '결근', TRUE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 40, 10, '재실', '출근', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 40, 9, '재실', '출근', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 40, 11, '재실', '출근', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 32, 8, '재실', '출근', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 35, 8, '부재', NULL, TRUE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 27, 5, '재실', '출근', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 24, 3, '부재', '결근', TRUE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 24, 4, '재실', '지각', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 16, 5, '재실', '출근', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 30, 8, '재실', '출근', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 32, 8, '재실', '출근', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(NULL, 40, 8, '재실', '출근', FALSE);
INSERT INTO ATTENDANCE_INFO(JAVACHIP_CODE,WORK_HOUR,REMAIN_VACATION,WORK_STATUS,ARRIVE_INFO,LEAVE_INFO)
    VALUES(1, 10, 0, '재실', '출근', FALSE);





SELECT 
    JAVACHIP_CODE,
    DAYS,
    DAY_SCHEDULE
FROM WORK_SCHEDULE_NEXTWEEK;

-- Error Code: 1062. Duplicate entry '월요일' for key 'WORK_SCHEDULE_NEXTWEEK.PRIMARY'
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(1,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(1,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(1,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(1,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(1,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(2,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(2,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(2,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(2,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(2,'금요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(3,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(3,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(3,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(3,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(3,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(4,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(4,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(4,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(4,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(4,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(5,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(5,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(5,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(5,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(5,'금요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(6,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(6,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(6,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(6,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(6,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(7,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(7,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(7,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(7,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(7,'금요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(8,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(8,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(8,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(8,'목요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(8,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(9,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(9,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(9,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(9,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(9,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(10,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(10,'화요일', '출장');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(10,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(10,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(10,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(11,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(11,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(11,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(11,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(11,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(12,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(12,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(12,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(12,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(12,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(13,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(13,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(13,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(13,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(13,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(14,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(14,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(14,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(14,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(14,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(15,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(15,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(15,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(15,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(15,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(16,'월요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(16,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(16,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(16,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(16,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(17,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(17,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(17,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(17,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(17,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(18,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(18,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(18,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(18,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(18,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(19,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(19,'화요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(19,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(19,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(19,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(20,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(20,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(20,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(20,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(20,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(21,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(21,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(21,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(21,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(21,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(22,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(22,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(22,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(22,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(22,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(23,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(23,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(23,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(23,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(23,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(24,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(24,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(24,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(24,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(24,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(25,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(25,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(25,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(25,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(25,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(26,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(26,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(26,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(26,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(26,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(27,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(27,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(27,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(27,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(27,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(28,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(28,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(28,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(28,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(28,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(29,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(29,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(29,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(29,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(29,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(30,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(30,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(30,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(30,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(30,'금요일', NULL);






-- 다음주 스케쥴 데이터
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(1,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(1,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(1,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(1,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(1,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(2,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(2,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(2,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(2,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(2,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(3,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(3,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(3,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(3,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(3,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(4,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(4,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(4,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(4,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(4,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(5,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(5,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(5,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(5,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(5,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(6,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(6,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(6,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(6,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(6,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(7,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(7,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(7,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(7,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(7,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(8,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(8,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(8,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(8,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(8,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(9,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(9,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(9,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(9,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(9,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(10,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(10,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(10,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(10,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(10,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(11,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(11,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(11,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(11,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(11,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(12,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(12,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(12,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(12,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(12,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(13,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(13,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(13,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(13,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(13,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(14,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(14,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(14,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(14,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(14,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(15,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(15,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(15,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(15,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(15,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(16,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(16,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(16,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(16,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(16,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(17,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(17,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(17,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(17,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(17,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(18,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(18,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(18,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(18,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(18,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(19,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(19,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(19,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(19,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(19,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(20,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(20,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(20,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(20,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(20,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(21,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(21,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(21,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(21,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(21,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(22,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(22,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(22,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(22,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(22,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(23,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(23,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(23,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(23,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(23,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(24,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(24,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(24,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(24,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(24,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(25,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(25,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(25,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(25,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(25,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(26,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(26,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(26,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(26,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(26,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(27,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(27,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(27,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(27,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(27,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(28,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(28,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(28,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(28,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(28,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(29,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(29,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(29,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(29,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(29,'금요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(30,'월요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(30,'화요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(30,'수요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(30,'목요일', NULL);
INSERT INTO WORK_SCHEDULE_NEXTWEEK(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(30,'금요일', NULL);