-- 일정조회
SELECT  
			A.*,
      B.JAVACHIP_CODE
 FROM WORK_SCHEDULE A
 JOIN (SELECT 
						 C.POSITION,
             C.JAVACHIP_NAME
				FROM JAVACHIP_MEMBER C) B ON A.JAVACHIP_CODE = B.JAVACHIP_CODE;
        
        
SELECT 
			 A.POSITION,
			 B.JAVACHIP_NAME
	FROM JAVACHIP_MEMBER A
	JOIN ATTENDANCE_INFO B ON A.JAVACHIP_CODE = B.JAVACHIP_CODE;

SELECT
      A.JAVACHIP_CODE,
      A.JAVACHIP_ID,
      A.JAVACHIP_NAME,
      A.POSITION,
      B.WORK_HOUR,
      B.REMAIN_VACATION,
      B.WORK_STATUS,
      B.ARRIVE_INFO,
      B.LEAVE_INFO
 FROM JAVACHIP_MEMBER A
 JOIN ATTENDANCE_INFO B ON A.JAVACHIP_CODE = B.JAVACHIP_CODE;
 
 
 
 UPDATE
				 WORK_SCHEDULE_NEXTWEEK
		 SET         
				DAY_SCHEDULE = '출장'
	WHERE DAYS = '월요일' AND
				JAVACHIP_CODE = 6;
        
        
DELETE
  FROM WORK_SCHEDULE_NEXTWEEK
 WHERE JAVACHIP_CODE = 3;
 
INSERT
	INTO WORK_SCHEDULE_NEXTWEEK
  ( JAVACHIP_CODE,
		DAYS,
    DAY_SCHEDULE)
VALUES  (3,'월요일', '출장')
			 ,(3,'화요일', '외근')
			 ,(3,'수요일', NULL)
			 ,(3,'목요일', '휴가')
			 ,(3,'금요일', NULL);
 
javachip_member
UPDATE
              WORK_SCHEDULE_NEXTWEEK
           SET
              DAY_SCHEDULE = '정상근무'
        WHERE DAYS = '월요일' AND JAVACHIP_CODE = 3;
        
DELETE FROM ATTENDANCE_INFO
WHERE JAVACHIP_CODE = 31;

DELETE FROM WORK_SCHEDULE
WHERE JAVACHIP_CODE = 31;  

DELETE FROM WORK_SCHEDULE_NEXTWEEK
WHERE JAVACHIP_CODE = 31;

DELETE FROM JAVACHIP_MEMBER
WHERE JAVACHIP_CODE = 31; 

SELECT
			A.JAVACHIP_CODE,
      A.JAVACHIP_NAME,
      A.POSITION,
			B.LEAVE_INFO
FROM JAVACHIP_MEMBER A
JOIN ATTENDANCE_INFO B ON A.JAVACHIP_CODE = B.JAVACHIP_CODE;

SELECT
       A.JAVACHIP_CODE,
       A.JAVACHIP_NAME,
       A.POSITION,
       B.DAY_SCHEDULE AS '금요일'
  FROM JAVACHIP_MEMBER A 
  JOIN WORK_SCHEDULE B ON A.JAVACHIP_CODE = B.JAVACHIP_CODE
 WHERE B.DAYS = '금요일';
 
SELECT
       A.JAVACHIP_CODE,
       A.JAVACHIP_NAME,
       A.POSITION,
       B.DAY_SCHEDULE
  FROM JAVACHIP_MEMBER A 
  JOIN WORK_SCHEDULE B ON A.JAVACHIP_CODE = B.JAVACHIP_CODE;
 
SELECT
			A.JAVACHIP_CODE,
      A.JAVACHIP_NAME,
      A.POSITION,
			B.REMAIN_VACATION
FROM JAVACHIP_MEMBER A
JOIN ATTENDANCE_INFO B ON A.JAVACHIP_CODE = B.JAVACHIP_CODE;
 
 
SELECT DAY_SCHEDULE AS '월요일'
FROM WORK_SCHEDULE_NEXTWEEK
WHERE DAYS = '월요일';

SELECT DAY_SCHEDULE AS '화요일'
FROM WORK_SCHEDULE_NEXTWEEK
WHERE DAYS = '화요일';

SELECT DAY_SCHEDULE AS '수요일'
FROM WORK_SCHEDULE_NEXTWEEK
WHERE DAYS = '화요일';

SELECT 
    A.JAVACHIP_CODE, 
    A.JAVACHIP_NAME,
    A.POSITION, 
    B.DAY_SCHEDULE
FROM
    JAVACHIP_MEMBER A
        JOIN
    WORK_SCHEDULE B ON A.JAVACHIP_CODE = B.JAVACHIP_CODE
GROUP BY JAVACHIP_CODE;

-- Error Code: 1055. Expression #4 of SELECT list is not in GROUP BY clause and 
-- contains nonaggregated column 'javachipdb.B.DAY_SCHEDULE' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

 
SELECT		
			JAVACHIP_CODE,
      DAY_SCHEDULE AS '월요일'
 FROM WORK_SCHEDULE_NEXTWEEK
 WHERE DAYS = '월요일';

SELECT		
			A.JAVACHIP_CODE,
       A.JAVACHIP_NAME,
       A.POSITION,
       B.DAY_SCHEDULE AS '월요일'
 FROM JAVACHIP_MEMBER A
 JOIN WORK_SCHEDULE B ON A.JAVACHIP_CODE = B.JAVACHIP_CODE
WHERE B.DAYS = '월요일'
UNION 
SELECT		
			A.JAVACHIP_CODE,
       A.JAVACHIP_NAME,
       A.POSITION,
       B.DAY_SCHEDULE AS '화요일'
 FROM JAVACHIP_MEMBER A
 JOIN WORK_SCHEDULE B ON A.JAVACHIP_CODE = B.JAVACHIP_CODE
WHERE B.DAYS = '화요일';

-- SELECT		
-- 			A.JAVACHIP_CODE,
--        A.JAVACHIP_NAME,
--        A.POSITION,
--        B.DAY_SCHEDULE AS '화요일'
--  FROM JAVACHIP_MEMBER A
--  JOIN WORK_SCHEDULE B ON A.JAVACHIP_CODE = B.JAVACHIP_CODE
-- WHERE B.DAYS = '화요일';
 

SELECT		
			JAVACHIP_CODE,
      JAVACHIP_NAME,
      POSITION
	FROM JAVACHIP_MEMBER
 UNION
 SELECT		
			  *
--  FROM WORK_SCHEDULE;
-- DELETE 테이블별칭1, 테이블별칭2, ...
--   FROM 테이블1 테이블별칭1, 테이블2 테이블별칭2, ...
--  WHERE 조건;
DELETE WS, WSN, ATI, MEM 
	FROM work_schedule  WS, 
	     work_schedule_NEXTWEEK WSN,
       ATTENDANCE_INFO ATI,
       JAVACHIP_MEMBER MEM          
WHERE JAVACHIP_CODE = 20;

DELETE FROM a, b 
    USING work_schedule a 
    LEFT JOIN work_schedule_NEXTWEEK b 
    ON a.JAVACHIP_CODE = b.JAVACHIP_CODE 
    WHERE b.JAVCHIP_CODE = '20';
    
DELETE FROM a, b, c, d 
    USING work_schedule a 
    LEFT JOIN work_schedule_NEXTWEEK b 
    LEFT JOIN work_schedule_NEXTWEEK c 
    ON a.JAVACHIP_CODE = b.JAVACHIP_CODE 
    WHERE b.JAVCHIP_CODE = '20'    

DELETE WS, WSN, ATI, MEM 
	FROM work_schedule  WS 
	JOIN work_schedule_NEXTWEEK WSN,
  JOIN ATTENDANCE_INFO ATI,
  JOIN JAVACHIP_MEMBER MEM          
WHERE WS.JAVACHIP_CODE = WSN.JAVACHIP_CODE AND WSN.JAVACHIP_CODE = ATI.JAVACHIP_CODE AND ATI.JAVACHIP_CODE = MEM.JAVACHIP_CODE AND JAVCHIP;


DELETE WS, WSN, ATI 
	FROM work_schedule  WS 
	JOIN work_schedule_NEXTWEEK WSN
  JOIN ATTENDANCE_INFO ATI         
WHERE WS.JAVACHIP_CODE = WSN.JAVACHIP_CODE 
AND WSN.JAVACHIP_CODE = ATI.JAVACHIP_CODE  
AND WS.JAVACHIP_CODE = 20;

Error Code: 1052. Column 'JAVACHIP_CODE' in where clause is ambiguous




