SELECT
       JAVACHIP_CODE,
       DAYS,
       DAY_SCHEDULE
FROM WORK_SCHEDULE;
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(1,'월요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(1,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(1,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(1,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(1,'금요일', '출장');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(2,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(2,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(2,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(2,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(2,'금요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(3,'월요일', '외근');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(3,'화요일', '외근');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(3,'수요일', '출장');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(3,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(3,'금요일', '출장');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(4,'월요일', '출장');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(4,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(4,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(4,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(4,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(5,'월요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(5,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(5,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(5,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(5,'금요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(6,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(6,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(6,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(6,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(6,'금요일', '외근');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(7,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(7,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(7,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(7,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(7,'금요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(8,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(8,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(8,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(8,'목요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(8,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(9,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(9,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(9,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(9,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(9,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(10,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(10,'화요일', '출장');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(10,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(10,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(10,'금요일', '출장');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(11,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(11,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(11,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(11,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(11,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(12,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(12,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(12,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(12,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(12,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(13,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(13,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(13,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(13,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(13,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(14,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(14,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(14,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(14,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(14,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(15,'월요일', '외근');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(15,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(15,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(15,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(15,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(16,'월요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(16,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(16,'수요일', '출장');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(16,'목요일', '외근');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(16,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(17,'월요일', '외근');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(17,'화요일', '외근');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(17,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(17,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(17,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(18,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(18,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(18,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(18,'목요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(18,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(19,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(19,'화요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(19,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(19,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(19,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(20,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(20,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(20,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(20,'목요일', '출장');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(20,'금요일', '출장');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(21,'월요일', '출장');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(21,'화요일', '출장');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(21,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(21,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(21,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(22,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(22,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(22,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(22,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(22,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(23,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(23,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(23,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(23,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(23,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(24,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(24,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(24,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(24,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(24,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(25,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(25,'화요일', '출장');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(25,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(25,'목요일', '외근');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(25,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(26,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(26,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(26,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(26,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(26,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(27,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(27,'화요일', '외근');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(27,'수요일', '외근');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(27,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(27,'금요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(28,'월요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(28,'화요일', '출장');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(28,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(28,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(28,'금요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(29,'월요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(29,'화요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(29,'수요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(29,'목요일', NULL);
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(29,'금요일', '출장');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(30,'월요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(30,'화요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(30,'수요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(30,'목요일', '휴가');
INSERT INTO WORK_SCHEDULE(JAVACHIP_CODE,DAYS,DAY_SCHEDULE)
VALUES(30,'금요일', '휴가');